### ISSUE TITLE
Can not deploy after upgrade to 2.2.0

### ISSUE THREAD

**Issue by emn178** [tronprotocol/tron-box#33]
2.1.10 has problem "CONTRACT_VALIDATE_ERROR" #32 
try to upgrade to 2.2.0, but it still doesn't work.
```
Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract has not been deployed on the network
    at /Users/emn178/inno/tron-joyso-contracts/node_modules/tronbox/build/webpack:/packages/tronwrap/index.js:136:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by GarryPlays** [comment]
ha lol, thought it was just me! neither, all kaputt

**Comment by sullof** [comment]
There was a critical error in the previous version. 
We just published TronBox 2.0.1, which supports the new java-tron 3.2 and fixes a couple of issues. Can you update and try again, please?
```
npm update -g tronbox
```

**Comment by sullof** [comment]
@GarryPlays This should be fixed. Reopen it, please, if not.

**Comment by infine8** [comment]
still doesn't work even for test "Metacoin" project.  nothing was changed

Using network 'shasta'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
ERROR: Unknown error: {
  "code": "CONTRACT_VALIDATE_ERROR",
  "message": "636f6e74726163742076616c6964617465206572726f72203a206163636f756e74206e6f7420657869737473"
}

**Comment by sullof** [comment]
That message is `contract validate error : account not exists`.
With TronBox 2.3.0, when there is an error during the deployment, you should see the link to get info about the transaction. Did you check it?

**Comment by sullof** [comment]
BTW,`metacoin-box` passes all the tests on Shasta without issue (I can share a video, if you don't believe me).
Is it possible that the account that you are using doesn't have enough energy or bandwidth?

**Comment by GarryPlays** [comment]
I would side with sullof here. I had the same issue, but since shasta reset your account will most likely not have any tron in it.
Of course with shasta refill being down since 2 days it seems mission impossible to refill your account :D
Or I am just hitting every single maintenance window they have.
Feel free to send me some shasta tron if you have TU1TYKYNKE928LvmXSSR7iiShr3SjexomY

**Comment by infine8** [comment]
OK. You're right, it was a bad account. it is better now but I get an error "contractRet":"OUT_OF_ENERGY". Any ideas how I can obtain energy in Shasta network? found only tronscan.org but there is no any opportunity to select an another network except mainnet

**Comment by GarryPlays** [comment]
https://www.trongrid.io/shasta/
It's enough to own tron. I think. I could deploy fine and I never got energy.
Hey check out https://trx.chibifighters.io if you like :D

**Comment by sullof** [comment]
@infine8 It can be a problem in the settings. Try to increase the `feeLimit` in `tronbox.js`

**Comment by sullof** [comment]
To request TRX on Shasta, look at https://www.trongrid.io/shasta/

**Comment by infine8** [comment]
The problem is I got TRX but I don't see no any opportunity to convert them to energy in Shasta and can't to check it's balance. TronLink shows balances only for Mainnet. I thought working with Ethereum was ugly, but this was much worse

**Comment by sullof** [comment]
@GarryPlays To freeze TRX (and for other stuff) you can install TronLink.

**Comment by GarryPlays** [comment]
@sullof huh? I am a living Popsicle. I think it was @infine8 asking. And yes, TronLink all the way.

**Comment by sullof** [comment]
@GarryPlays You are right!
It's Monday morning, my brain is still not fully working :-)
